### ISSUE TITLE
Can't set Task Scheduling

### ISSUE THREAD

**Issue by sky86857322** [humhub/humhub-modules-tasks#123]
When I choose to submit it all day, the start date will be filled in today, and it will be 1970/01/01.

**Comment by buddh4** [comment]
- Which HumHub version is in use?
- Which module version is in use?
- Which Language is in use "Account settings -> Settings -> Language"?

**Comment by sky86857322** [comment]
> * Which HumHub version is in use?
> * Which module version is in use?
> * Which Language is in use "Account settings -> Settings -> Language"?

1 1.6.3
2 task 1.3.6
3 simplified Chinese

**Comment by sky86857322** [comment]
This error occurs when using the language "simplified Chinese, traditional Chinese, Korean"
