### ISSUE TITLE
Media player broken in comments on task list view

### ISSUE THREAD

**Issue by st5000** [humhub/humhub-modules-tasks#128]
When display task comments containing files (e.g mp3), media player is not functional and showed as this:

![image](https://user-images.githubusercontent.com/57590912/98674759-91328200-2359-11eb-9528-cbea79a3ce24.png)

**Comment by buddh4** [comment]
Could not recreate this:

![grafik](https://user-images.githubusercontent.com/9800854/98686209-921ee000-2368-11eb-83c7-3806a0fc9957.png)


Which HumHub version are you using?

**Comment by st5000** [comment]
Using HH 1.7.0

Could you try trough space left sidebar : Space -> Tasks -> select task to expand comments.

**Comment by buddh4** [comment]
Can you check the [developer console of your browser](https://docs.humhub.org/docs/about/support#errors-and-logs) for any errors and check the network tab if there are any resources which could not be loaded.

**Comment by st5000** [comment]
Getting this:
```
WARN - humhub.modules.action: undefined ReferenceError: jPlayerPlaylist is not defined
...
humhub-app.js:258:20765
```

**Comment by buddh4** [comment]
Did you try to [flush the cache](https://docs.humhub.org/docs/admin/troubleshooting#clear-cache) if yes please check the network tab for erroneous requests.

**Comment by st5000** [comment]
Issue remain after HH cache (Redis), assets and browser flush. No network error.
