### ISSUE TITLE
Ability to drag tasks between lists

### ISSUE THREAD

**Issue by olantrust** [humhub/humhub-modules-tasks#134]
One can currently rearrange tasks within a list, and rearrange lists, but not move tasks between lists, which would be ideal.

It would move the tasks app to usefully serve many of the 'kanban' features, and improve workflow intuitiveness, ease, and speed.

**Comment by buddh4** [comment]
Draggin a taks from one list to another works fine for me?

**Comment by olantrust** [comment]
> Draggin a taks from one list to another works fine for me? What happens if you try to drag an taks to another list?

Apologies, it is working in Chrome, and Firefox, just not my Firefox beta, should've checked first! :s
