### ISSUE TITLE
fehlende Weiterleitung zum Login

### ISSUE THREAD

**Issue by tobciu** [humhub/humhub-modules-tasks#17]
Wenn man noch nicht in HumHub angemeldet ist, aber über die E-Mail auf 'online ansehen' eines Tasks klickt, erhält man eine Fehlermeldung, hier wäre es besser wenn man zum Login weitergeleitet wird

**Comment by buddh4** [comment]
Will be fixed with https://github.com/humhub/humhub/commit/fdb9179056c89efe8df879bfef18f7c2a35c8799
