### ISSUE TITLE
[FEATURE] Reorder ans subtasks

### ISSUE THREAD

**Issue by devcline** [humhub/humhub-modules-tasks#27]
Hello

Can we add please a drag and drop reorder for the tasks?

And what about a subtasks? is it in future?

thanks

**Comment by harry5k** [comment]
oh yes subtasks would be nice, i need subtasks please!
What do you think about a headline and a descriptionline for the tasks?

**Comment by levikoenig** [comment]
+1 Would love to see some better task/project management support

**Comment by buddh4** [comment]
Reordering is already implemented, subtasks was already mentioned here: https://github.com/humhub/humhub-modules-tasks/issues/7
