### ISSUE TITLE
Permission over Task Edit, Task View

### ISSUE THREAD

**Issue by dulisha** [humhub/humhub-modules-tasks#39]
1. Members are able to see all tasks from Space. Should be pointed only tasks that are related with them
2. Members, and not space admins are able to edit, delete, assign more users to task. This is not good. It's need permission to control option to control this options. Who can edit, mark task as completed, or delete it.

**Comment by buddh4** [comment]
The permissions were refactored, the search view by default filters for assigned tasks.
