### ISSUE TITLE
Assigning users to task afterwards

### ISSUE THREAD

**Issue by dmitriy-luch** [humhub/humhub-modules-tasks#4]
Once a task is created there is no possibility to assign users to it.
Users can be assigned during creation process which is not very comfortable.

**Comment by michaelh99** [comment]
So, this was closed but does that mean one should be able to assign tasks after creation?  Because I'm unable to in the latest versions of humhub and the tasks module.  This was closed without comment

**Comment by luke-** [comment]
![image](https://user-images.githubusercontent.com/4736168/118515103-5d377f80-b735-11eb-83dc-687d5181f1ed.png)

You can edit and assign user to the task here.

**Comment by michaelh99** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/4736168/118515103-5d377f80-b735-11eb-83dc-687d5181f1ed.png)
> 
> You can edit and assign user to the task here.

I can't.  While it lists users, they're grayed out and can't be selected.
I'm a site admin and admins should have access for modifying (default-allow)

**Comment by luke-** [comment]
You can only select users which are member of the Space.

**Comment by michaelh99** [comment]
> You can only select users which are member of the Space.

Well.  d**n.  Is my face red.

Wish there were a more obvious UX indicator of that but I'm embarrassed I didn't think of that aspect.

**Comment by luke-** [comment]
No problem but the UX indicator would definitely be helpful.
