### ISSUE TITLE
Successful registration with a needed registration Code

### ISSUE THREAD

**Issue by MarvinZiegenhorn** [humhub/humhub-modules-tasks#40]
Hi Folks, first of all thanks in advance for helping me.
I want to "open" a new HumHub Installation just for People which have got a Registration Code from me.
So first everyone could do a Registration. After that the User gets a Mail for finishing the Registration. And in this webform should be a new field to enter the Registration Code.

How could i do that?

Thanks in Advance
Bye Marvin

**Comment by buddh4** [comment]
Not related to task module.
