### ISSUE TITLE
Problem after update to 1.0.6

### ISSUE THREAD

**Issue by sam11fr** [humhub/humhub-modules-tasks#41]
Hi,
problem after update to 1.0.6.
Humhub 1.1.2

LOG1
| 17683 |     1 | yii\base\ErrorException:4 |  1485118112.897 | [192.168.0.165][11][78dnoqeiu0oel3sm1fvnsmat15] | exception 'yii\base\ErrorException' with message 'syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'' in /var/www/html/protected/modules/tasks/views/task/edit.php:45
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main} 

LOG2
| 17684 |     4 | application               | 1485118112.8121 | [192.168.0.165][11][78dnoqeiu0oel3sm1fvnsmat15] | $_GET = [
    'r' => 'tasks/task/edit'
    'sguid' => '4fe56c19-3dbe-4ea1-8cad-8affe2dfd291'
]

LOG3
$_SERVER = [
    'UNIQUE_ID' => 'WIUaoFwB6rXAUKbP2@2MOgAAAAA'
    'HTTP_X_CSRF_TOKEN' => 'Z0guUy1wYXgPH1lkY0ECEz0PYSN4JApIEH8eFGs1AC8Ff0IBVSgzCA=='
    'HTTP_ACCEPT' => 'text/html, */*; q=0.01'
    'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest'
    'HTTP_REFERER' => 'http://192.168.0.15/index.php?r=tasks%2Ftask%2Fshow&sguid=4fe56c19-3dbe-4ea1-8cad-8affe2dfd291'
    'HTTP_ACCEPT_LANGUAGE' => 'fr-FR'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393'
    'HTTP_HOST' => '192.168.0.15'
    'HTTP_DNT' => '1'
    'HTTP_CONNECTION' => 'Keep-Alive'
    'HTTP_COOKIE' => 'PHPSESSID=78dnoqeiu0oel3sm1fvnsmat15; _csrf=b7ce75b74656ba2bac4a1373225a4d8369295991cd9e9d1808160f24bcccf873a%3A2%3A%7Bi%3A0%3Bs%3A5%3A%22_csrf%22%3Bi%3A1%3Bs%3A32%3A%22hWw7N1ckZGOpUTk0w70GFEaWb7lRxXRp%22%3B%7D; pm_space-members-panel=expanded; _ga=GA1.1.1568036258.1484687099; _identity=a1990d9ca94b90daca59eaf43431c912b3498e446bb46eb04c581f9b7f941affa%3A2%3A%7Bi%3A0%3Bs%3A9%3A%22_identity%22%3Bi%3A1%3Bs%3A51%3A%22%5B11%2C%22de8681d4-b6ac-4121-b269-9c89f7d79ad3%22%2C2592000%5D%22%3B%7D; _gat=1'
    'PATH' => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
    'SERVER_SIGNATURE' => ''
    'SERVER_SOFTWARE' => 'Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips'
    'SERVER_NAME' => '192.168.0.15'
    'SERVER_ADDR' => '192.168.0.15'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '192.168.0.165'
    'DOCUMENT_ROOT' => '/var/www/html'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => '/var/www/html'
    'SERVER_ADMIN' => 'root@localhost'
    'SCRIPT_FILENAME' => '/var/www/html/index.php'
    'REMOTE_PORT' => '49389'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => 'r=tasks%2Ftask%2Fedit&sguid=4fe56c19-3dbe-4ea1-8cad-8affe2dfd291'
    'REQUEST_URI' => '/index.php?r=tasks%2Ftask%2Fedit&sguid=4fe56c19-3dbe-4ea1-8cad-8affe2dfd291'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1485118112.81
    'REQUEST_TIME' => 1485118112
] |

Bests regards

**Comment by yrosner** [comment]
The error is caused by the use of ::class in edit.php line 45
::class is not compatible with PHP 5.4 (it is PHP >= 5.5)

I think it should be changed to `... \humhub\modules\user\widgets\UserPickerField::className()`

**Comment by sam11fr** [comment]
Hello.
Thanks a lot for your feedback. Indeed, I have updated PHP to version 5.6 and it's good. Everything works.
Kind regards
Sam
