### ISSUE TITLE
The task description in task manager module is diseapering.

### ISSUE THREAD

**Issue by rzusto** [humhub/humhub-modules-tasks#42]
The task description in task manager module is diseapering.
The video show this problem:
https://youtu.be/STuBdQ9JrXk
This problem appeared after upgrading to latest version of module.

**Comment by stothew** [comment]
I hanent´t noticed yet. But i can confirm. It happend also to all tasks done till now.

http://imgur.com/a/1JmQh

+1

**Comment by stothew** [comment]
I fixed it.
You can just change:
`<? Html::encode($task->title); ?> `
to
`<?= Html::encode($task->title); ?>`
on /views/task/show.php (line 237)

I also did a pull request.

**Comment by rzusto** [comment]
ok, it works. Thanks!
