### ISSUE TITLE
Error after organizing task in spaces

### ISSUE THREAD

**Issue by Oktavianus13** [humhub/humhub-modules-tasks#69]
Hi there,  

Seems I have problem with my humhub installation, when I click the task on the space menu it show  error  :

>  yii\base\InvalidConfigException: Unable to locate message source for category 'MeetingModule.base'. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/i18n/I18N.php,

Seems its happened after I had reorganizing my task using new feature tasklist and task item (humhub 1.2.7 task version: 1.1.6 ). The funny things is the other space that I had done the same does not have this problem.

Any suggestion how to debug of identify the data caused this error? Any idea is appreciated.
Thank you

**Comment by Oktavianus13** [comment]
While reading the error log, I just notice that the error occured when it trying rendering task list from a task list id. 

> 1. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/i18n/I18N.php at line 200
> 2. in /var/www/humhub/humhub-1.2.4/protected/humhub/components/i18n/I18N.php at line 168 – yii\i18n\I18N::getMessageSource('MeetingModule.base')
> 3. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/i18n/I18N.php at line 88 – humhub\components\i18n\I18N::getMessageSource('MeetingModule.base')
> 4. in /var/www/humhub/humhub-1.2.4/protected/humhub/components/i18n/I18N.php at line 139 – yii\i18n\I18N::translate('MeetingModule.base', 'Delete', [], 'en-US')
> 5. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/BaseYii.php at line 509 – humhub\components\i18n\I18N::translate('MeetingModule.base', 'Delete', [], 'en-US')
> 6. in /var/www/humhub/humhub-1.2.4/protected/modules/tasks/widgets/lists/views/completedTaskListItem.php at line 21 – yii\BaseYii::t('MeetingModule.base', 'Delete')
> 7. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 330 – require('/var/www/humhub/humhub-1.2.4/pro...')
> 8. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 250 – yii\base\View::renderPhpFile('/var/www/humhub/humhub-1.2.4/pro...', ['canEdit' => true, 'taskList' => humhub\modules\tasks\models\lists\TaskList, 'options' => ['class' => 'media', 'data' => ['reload-url' => '/index.php?r=tasks%2Flist%2Fload...', 'ui-widget' => 'task.list.CompletedTaskListViewI...'], 'id' => 'h174273w280']])
> 9. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 152 – yii\base\View::renderFile('/var/www/humhub/humhub-1.2.4/pro...', ['canEdit' => true, 'taskList' => humhub\modules\tasks\models\lists\TaskList, 'options' => ['class' => 'media', 'data' => ['reload-url' => '/index.php?r=tasks%2Flist%2Fload...', 'ui-widget' => 'task.list.CompletedTaskListViewI...'], 'id' => 'h174273w280']], humhub\modules\tasks\widgets\lists\CompletedTaskListItem)
> 10. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/Widget.php at line 234 – yii\base\View::render('completedTaskListItem', ['canEdit' => true, 'taskList' => humhub\modules\tasks\models\lists\TaskList, 'options' => ['class' => 'media', 'data' => ['reload-url' => '/index.php?r=tasks%2Flist%2Fload...', 'ui-widget' => 'task.list.CompletedTaskListViewI...'], 'id' => 'h174273w280']], humhub\modules\tasks\widgets\lists\CompletedTaskListItem)
> 11. in /var/www/humhub/humhub-1.2.4/protected/modules/tasks/widgets/lists/CompletedTaskListItem.php at line 44 – yii\base\Widget::render('completedTaskListItem', ['canEdit' => true, 'taskList' => humhub\modules\tasks\models\lists\TaskList, 'options' => ['class' => 'media', 'data' => ['reload-url' => '/index.php?r=tasks%2Flist%2Fload...', 'ui-widget' => 'task.list.CompletedTaskListViewI...'], 'id' => 'h174273w280']])
> 12. in /var/www/humhub/humhub-1.2.4/protected/humhub/components/Widget.php at line 57 – humhub\modules\tasks\widgets\lists\CompletedTaskListItem::run()
> 13. in /var/www/humhub/humhub-1.2.4/protected/modules/tasks/widgets/lists/views/_closedItem.php at line 10 – humhub\components\Widget::widget(['taskList' => humhub\modules\tasks\models\lists\TaskList, 'canEdit' => true, 'class' => 'humhub\modules\tasks\widgets\lis...'])
> 14. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 330 – require('/var/www/humhub/humhub-1.2.4/pro...')
> 15. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 250 – yii\base\View::renderPhpFile('/var/www/humhub/humhub-1.2.4/pro...', ['model' => humhub\modules\tasks\models\lists\TaskList, 'key' => 11, 'index' => 0, 'widget' => yii\widgets\ListView, ...])
> 16. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/base/View.php at line 152 – yii\base\View::renderFile('/var/www/humhub/humhub-1.2.4/pro...', ['model' => humhub\modules\tasks\models\lists\TaskList, 'key' => 11, 'index' => 0, 'widget' => yii\widgets\ListView, ...], null)
> 17. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/widgets/ListView.php at line 191 – yii\base\View::render('@tasks/widgets/lists/views/_clos...', ['model' => humhub\modules\tasks\models\lists\TaskList, 'key' => 11, 'index' => 0, 'widget' => yii\widgets\ListView, ...])
> 18. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/widgets/ListView.php at line 124 – yii\widgets\ListView::renderItem(humhub\modules\tasks\models\lists\TaskList, 11, 0)
> 19. in /var/www/humhub/humhub-1.2.4/protected/vendor/yiisoft/yii2/widgets/BaseListView.php at line 159 – yii\widgets\ListView::renderItems()


So I update the task list id to null for all that task list id .
seems the problem somehow fixed by that  update.

**Comment by Oktavianus13** [comment]
the issue has been identified, whenever a task in a list is completed using finish task button, the error occur.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub-modules-tasks/commit/65ee425f38010f9b26cba27147757ea357ab5040
