### ISSUE TITLE
[Process request] Adding a translation pack

### ISSUE THREAD

**Issue by kupjohn** [humhub/humhub-modules-tasks#77]
Hi,

I have seen that there is a french translation pack, howerver, I don't know how to use it?
Looking forward a process to make it available in the platform.

Regards,

Kim

**Comment by kupjohn** [comment]
Hi,

Anyone to help me on how to use the translation pack?

Regards,

Kim

**Comment by buddh4** [comment]
Translations are contained within the module itself. You can contribute within http://translate.humhub.org/dashboard.
