### ISSUE TITLE
Emails is sent to all users on rejection or completion of task

### ISSUE THREAD

**Issue by guilhermecoimma** [humhub/humhub-modules-tasks#80]
When a task is concluded or rejected all users receive email about the update even if they is not assigned to the task.

**Comment by buddh4** [comment]
Cannot confirm this, only assigned users are informed about rejection/completion.

**Comment by guilhermecoimma** [comment]
I have this problem, after the updates of #81 the problem is solved. 

Has any problem to use $this->task->filterResponsibleAssigned() instead $this->task->getTaskAssignedUsers(true)?

In my case this resolve the problem.

**Comment by guilhermecoimma** [comment]
All users of the network. I do exactly you described.

**Comment by buddh4** [comment]
I can't reproduce this issue could you try the following:

```
public function getTaskAssignedUsers($filterOutResponsibleUsers = false)
    {
        $query = $this->hasMany(User::class, ['id' => 'user_id'])->via('assignedTaskUsers');

        if($filterOutResponsibleUsers) {
            $responsible = $this->getTaskResponsibleUsers()->select(['id']);
            $query->where(['not in', 'user.id', $responsible]);
            Yii::error($query->createCommand()->rawSql);
        }

        return $query;
    }
```

Which logs something like this in my case:

```
SELECT * FROM `user` WHERE (`user`.`id` NOT IN (SELECT `id` FROM `user` WHERE `id`=1)) AND (`id` IN (3, 7))
```

**Comment by St-Ki** [comment]
Today i got the same issue. Working with Humhub 1.3.5 and Tasks Module 1.2.1.

I rejected a task (two people involved) in a PRIVATE space with only 6 members and the e-mail notification was sent to all 114 Humhub users!

My phone is permanently ringing because of this e-mail!

**Comment by buddh4** [comment]
Unfortunately could still not recreate this, but I'll use the other query as suggested by @guilhermecoimma
