### ISSUE TITLE
Users can’t reset their own task

### ISSUE THREAD

**Issue by rcheetah** [humhub/humhub-modules-tasks#82]
If a task is assigned to a user, and he completes the task (by accident), he is not able to reset the task again. I don’t know if this is a bug, or a wanted behavior. 

Generally it would be nice if an admin would be able to modify the module, so that users have the permission to edit tasks altogether. This could even be set for each list, so there is more control over  the tasks module.

**Comment by rcheetah** [comment]
I’m sorry I was to fast creating this issue. I grasped the concept of assigned users and responsible users now. But I would appreciate a „simple-mode“ and apart from that some documentation, because this module has grown far beyond a simple Todo-List, and it’s not so easy to understand as you may think ^^

**Comment by buddh4** [comment]
We'll work on the module descriptions in v1.4, but there already is a small info box in the Assignment tab with a short description.
