### ISSUE TITLE
table misssing after deactivating the task-module 

### ISSUE THREAD

**Issue by ferkulum** [humhub/humhub-modules-tasks#88]
I deactivated the modul "tasks" which did not work (no error message, still appeared as active). Now I cannot access HumHub anymore and the following error occurs:

> exception 'yii\base\InvalidConfigException' with message 'The table does not exist: task' in /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php:382
> Stack trace:
> #0 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(413): yii\db\ActiveRecord::getTableSchema()
> #1 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(492): yii\db\ActiveRecord->attributes()
> #2 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(289): yii\db\BaseActiveRecord->hasAttribute('status')
> #3 /var/www/html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(192): yii\db\BaseActiveRecord->__get('status')
> #4 /var/www/html/humhub/protected/modules/tasks/models/Task.php(177): humhub\modules\content\components\ContentActiveRecord->__get('status')
> #5 /var/www/html/humhub/protected/modules/tasks/models/Task.php(129): humhub\modules\tasks\models\Task->__get('status')
> #6 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\tasks\models\Task->init()
> #7 /var/www/html/humhub/protected/humhub/modules/content/components/ContentActiveRecord.php(146): yii\base\BaseObject->__construct(Array)
> #8 [internal function]: humhub\modules\content\components\ContentActiveRecord->__construct(Array, NULL, Array)
> #9 /var/www/html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(375): ReflectionClass->newInstanceArgs(Array)
> #10 /var/www/html/humhub/protected/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('humhub\\modules\\...', Array, Array)
> #11 /var/www/html/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('humhub\\modules\\...', Array)
> #12 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/StaticInstanceTrait.php(37): yii\BaseYii::createObject('humhub\\modules\\...')
> #13 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(447): yii\base\Model::instance()
> #14 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(146): yii\db\ActiveQuery->buildJoinWith()
> #15 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/QueryBuilder.php(227): yii\db\ActiveQuery->prepare(Object(yii\db\mysql\QueryBuilder))
> #16 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(316): yii\db\QueryBuilder->build(Object(humhub\modules\content\components\ActiveQueryContent))
> #17 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/Query.php(237): yii\db\ActiveQuery->createCommand(NULL)
> #18 /var/www/html/humhub/protected/vendor/yiisoft/yii2/db/ActiveQuery.php(133): yii\db\Query->all(NULL)
> #19 /var/www/html/humhub/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(566): yii\db\ActiveQuery->all()
> #20 /var/www/html/humhub/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(143): humhub\modules\calendar\interfaces\AbstractCalendarQuery->all()
> #21 /var/www/html/humhub/protected/modules/calendar/interfaces/AbstractCalendarQuery.php(152): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForFilter(Object(DateTime), Object(DateTime), NULL, Array, '5')
> #22 /var/www/html/humhub/protected/modules/tasks/integration/calendar/TaskCalendar.php(51): humhub\modules\calendar\interfaces\AbstractCalendarQuery::findForEvent(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #23 /var/www/html/humhub/protected/modules/tasks/Events.php(56): humhub\modules\tasks\integration\calendar\TaskCalendar::addItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #24 [internal function]: humhub\modules\tasks\Events::onFindCalendarItems(Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #25 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Array, Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #26 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger(Object(humhub\modules\calendar\interfaces\CalendarService), 'findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #27 /var/www/html/humhub/protected/modules/calendar/interfaces/CalendarService.php(110): yii\base\Component->trigger('findItems', Object(humhub\modules\calendar\interfaces\CalendarItemsEvent))
> #28 /var/www/html/humhub/protected/modules/calendar/interfaces/CalendarService.php(145): humhub\modules\calendar\interfaces\CalendarService->getCalendarItems(Object(DateTime), Object(DateTime), Array, NULL, '5')
> #29 /var/www/html/humhub/protected/modules/calendar/widgets/UpcomingEvents.php(41): humhub\modules\calendar\interfaces\CalendarService->getUpcomingEntries(NULL, '31', '5')
> #30 /var/www/html/humhub/protected/humhub/components/Widget.php(58): humhub\modules\calendar\widgets\UpcomingEvents->run()
> #31 /var/www/html/humhub/protected/humhub/widgets/BaseStack.php(85): humhub\components\Widget::widget(Array)
> #32 /var/www/html/humhub/protected/humhub/components/Widget.php(58): humhub\widgets\BaseStack->run()
> #33 /var/www/html/humhub/protected/humhub/modules/dashboard/views/dashboard/index.php(31): humhub\components\Widget::widget(Array)
> #34 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(336): require('/var/www/html/h...')
> #35 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/var/www/html/h...', Array)
> #36 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/var/www/html/h...', Array, Object(humhub\modules\dashboard\controllers\DashboardController))
> #37 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render('index', Array, Object(humhub\modules\dashboard\controllers\DashboardController))
> #38 /var/www/html/humhub/protected/humhub/modules/dashboard/controllers/DashboardController.php(70): yii\base\Controller->render('index', Array)
> #39 [internal function]: humhub\modules\dashboard\controllers\DashboardController->actionIndex()
> #40 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #41 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> #42 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
> #43 /var/www/html/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('dashboard/dashb...', Array)
> #44 /var/www/html/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
> #45 /var/www/html/humhub/index.php(25): yii\base\Application->run()
> #46 {main}

HumHub version: 1.3.10
Modul version :  1.2.2

What can I do?

**Comment by ferkulum** [comment]
Hi again, is there anybody who could help? 

Thank you & all the best,
David

**Comment by buddh4** [comment]
Try removing the module from the table `module_enabled`.
